### ISSUE TITLE
Colored PointCloud support?

### ISSUE THREAD

**Issue by ryanmjacobs** [curiosity-inc/azure-kinect-dk-unity#2]
I was wondering if your codebase supports rendering colored pointclouds. No worries if it doesn't... I was just curious and couldn't tell by the screenshots in the README.

On my system (different code), I was able to use Unity to maneuver around the pointcloud in 3D. Something like this:

![pointcloud gif](https://user-images.githubusercontent.com/4251257/63483399-1bd74a80-c451-11e9-9a2b-6747f2b399dc.gif)

(I know it's hard to tell because there isn't any motion in the capture, but that is indeed real-time.)

I was wondering if something similar was already implemented here.

**Comment by thorikawa** [comment]
No, it is not implemented.
