### ISSUE TITLE
AzureKinectException: result = K4A_RESULT_FAILED

### ISSUE THREAD

**Issue by Ramanan-Aximsoft** [curiosity-inc/azure-kinect-dk-unity#3]
Hi,

I cloned the code and followed your steps. 
I upgraded as per the mentioned requirement.
Still, I face the issue. Can you help me in solving this.

Regards,
Ramanan.
![Capture](https://user-images.githubusercontent.com/54445325/63602146-6b9a4b00-c5e4-11e9-9bf2-e55132f8667c.JPG)

**Comment by Ramanan-Aximsoft** [comment]
This is my error log----------------


{"level":"info","message":"Starting Server","timestamp":"2019-08-23T13:46:10.850Z"}
{"level":"info","message":"Server started on port [51556]","timestamp":"2019-08-23T13:46:10.856Z"}
{"level":"info","message":"Health Request received","timestamp":"2019-08-23T13:46:11.013Z"}
{"level":"error","message":"[Unity Package Manager (Upm)]\nParent process [25468] was terminated","timestamp":"2019-08-23T13:46:15.578Z"}

**Comment by webleahy** [comment]
@Ramanan-Aximsoft I also have this same issue.  I followed the same steps as you.

**Comment by Ramanan-Aximsoft** [comment]
I solved it by adding all the dlls. It worked awesome.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by github-jinwei** [comment]
I add all the dlls but it's failed:
AzureKinectException: result = K4A_RESULT_FAILED
Microsoft.Azure.Kinect.Sensor.AzureKinectException.ThrowIfNotSuccess (Microsoft.Azure.Kinect.Sensor.NativeMethods+k4a_result_t result) (at Assets/AzureKinectDK/Scripts/M4A/AzureKinectException.cs:62)
Microsoft.Azure.Kinect.Sensor.Device.StartCameras (Microsoft.Azure.Kinect.Sensor.DeviceConfiguration configuration) (at Assets/AzureKinectDK/Scripts/M4A/Device.cs:271)
DebugRenderer.OnEnable () (at Assets/AzureKinectDK/Examples/Scripts/DebugRenderer.cs:26)

**Comment by github-jinwei** [comment]
![image](https://user-images.githubusercontent.com/16819190/71443989-46137e80-2749-11ea-9b90-3689bce78802.png)

**Comment by chenritiana** [comment]
How to solve this problem? I add these dlls but also useless.
