### ISSUE TITLE
K4A_WAIT_RESULT_FAILED

### ISSUE THREAD

**Issue by husakm** [curiosity-inc/azure-kinect-dk-unity#7]
Hi

I am getting permanently following bug report after typically 30-60 second
code run. It happen in both Unity GUI and in compiled .exe version ...
Any hint what can be wrong?

AzureKinectException: result = K4A_WAIT_RESULT_FAILED
Microsoft.Azure.Kinect.Sensor.AzureKinectException.ThrowIfNotSuccess (Microsoft.Azure.Kinect.Sensor.NativeMethods+k4a_wait_result_t result) (at Assets/AzureKinectDK/Scripts/M4A/AzureKinectException.cs:74)
Microsoft.Azure.Kinect.Sensor.BodyTracking.BodyTracker.EnqueueCapture (Microsoft.Azure.Kinect.Sensor.Capture capture, System.Int32 timeoutInMS) (at Assets/AzureKinectDK/Scripts/M4ABT/BodyTracker.cs:41)
DebugRenderer.Update () (at Assets/AzureKinectDK/Examples/Scripts/DebugRenderer.cs:57)

**Comment by stjung65** [comment]
Have you fixed your problem?
I have no error in Unity GUI run.
But I have the same error in compiled version.

**Comment by husakm** [comment]
No, I was not able to find the bug.
I have insted encoded a C++ C# interface doing the whole Unity/Kinect communication job myself - but it si not a free project.
Btw. Microsoft had inlcuded in the SDK ther C# interface in latest body trakcing drivers ... If you are familiat with external .dll usage in C# you shoudl give a tray to it ....

**Comment by stjung65** [comment]
Thank you very much.
I will try.

Sungtae Jung

**Comment by tchemaly** [comment]
Did anyone solve this issue? I am having this problem.

**Comment by husakm** [comment]
tchemaly:
There is no need to use the code from this page anymore. Par of the latest (1.0.0) Azure Kinect Body Tracking SDK is a C# wrapper from Microsoft. The Microsoft examples for the SDK contains a functional body tracking sample code. Tested by me and found functional.
See:
https://docs.microsoft.com/en-us/azure/kinect-dk/body-sdk-download
[Feature] Add C# wrapper to the msi installer.
And primary see the Unity sample code:
https://github.com/microsoft/Azure-Kinect-Samples/tree/master/body-tracking-samples/sample_unity_bodytracking

**Comment by stjung65** [comment]
Thank you very much for your comment,

Best Regards,

Sungtae Jung
